name: Android Build and Fix

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
 
      - name: Build and fix errors
        run: |
          ./gradlew build
          ./gradlew lintFix
 
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -am "Fix build errors" --allow-empty
 
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
